# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-05 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanager', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal', models.CharField(blank=True, max_length=25, null=True, verbose_name='\u5de5\u4f5c\u6d41\u6a21\u578b')),
                ('instance', models.CharField(blank=True, max_length=25, null=True, verbose_name='\u5de5\u4f5c\u6d41\u5b9e\u4f8b')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('submit_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='\u52a8\u4f5c')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u63cf\u8ff0')),
                ('submit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_submit_user_set', to='usermanager.UserProfile', verbose_name='\u63d0\u4ea4\u4eba')),
            ],
            options={
                'verbose_name': '\u5de5\u4f5c\u6d41\u5386\u53f2',
                'verbose_name_plural': '\u5de5\u4f5c\u6d41\u5386\u53f2',
            },
        ),
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, null=True, verbose_name='\u5de5\u4f5c\u6d41\u540d\u79f0')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
                ('app_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u5e94\u7528\u540d\u79f0')),
                ('model_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u6a21\u578b\u540d\u79f0')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='\u5173\u8054\u8868\u5355')),
            ],
            options={
                'verbose_name': '\u5de5\u4f5c\u6d41\u6a21\u578b',
                'verbose_name_plural': '\u5de5\u4f5c\u6d41\u6a21\u578b',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name='\u8282\u70b9\u540d\u79f0')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u8282\u70b9\u7f16\u53f7')),
                ('notice_type', models.IntegerField(blank=True, choices=[(1, '\u90ae\u4ef6\u901a\u77e5'), (2, '\u77ed\u4fe1\u901a\u77e5')], default=1, null=True, verbose_name='\u901a\u77e5\u7c7b\u578b')),
                ('handler_type', models.IntegerField(blank=True, choices=[(1, '\u7528\u6237'), (2, '\u89d2\u8272'), (3, '\u90e8\u95e8'), (4, '\u5c97\u4f4d')], default=1, null=True, verbose_name='\u7ba1\u7406\u8005\u7c7b\u578b')),
                ('code_branch', models.BooleanField(default=False, verbose_name='\u5206\u652f')),
                ('start', models.BooleanField(default=False, verbose_name='\u5f00\u59cb')),
                ('stop', models.BooleanField(default=False, verbose_name='\u7ed3\u675f')),
                ('can_approve', models.BooleanField(default=False, verbose_name='\u540c\u610f')),
                ('can_deny', models.BooleanField(default=False, verbose_name='\u62d2\u7edd')),
                ('can_transfer', models.BooleanField(default=False, verbose_name='\u8f6c\u4ea4')),
                ('can_reject', models.BooleanField(default=False, verbose_name='\u9a73\u56de')),
                ('can_finish', models.BooleanField(default=False, verbose_name='\u5b8c\u6210')),
                ('can_not_finish', models.BooleanField(default=False, verbose_name='\u672a\u5b8c\u6210')),
                ('can_delete', models.BooleanField(default=False, verbose_name='\u5220\u9664')),
                ('handler_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_handler_department_set', to='usermanager.Department', verbose_name='\u6307\u5b9a\u90e8\u95e8')),
                ('handler_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_handler_position_set', to='usermanager.UserProfile', verbose_name='\u6307\u5b9a\u5c97\u4f4d')),
                ('handler_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_handler_roles_set', to='usermanager.UserProfile', verbose_name='\u6307\u5b9a\u89d2\u8272')),
                ('handler_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_handler_user_set', to='usermanager.UserProfile', verbose_name='\u6307\u5b9a\u7528\u6237')),
                ('modal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_modal_set', to='workflow.Modal', verbose_name='\u5de5\u4f5c\u6d41\u6a21\u578b')),
            ],
            options={
                'verbose_name': '\u5de5\u4f5c\u6d41\u8282\u70b9',
                'verbose_name_plural': '\u5de5\u4f5c\u6d41\u8282\u70b9',
            },
        ),
        migrations.CreateModel(
            name='NodeBranch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name='\u5206\u652f\u540d\u79f0')),
                ('branch_condition', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5206\u652f\u6761\u4ef6')),
                ('branch_field', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5206\u652f\u5b57\u6bb5')),
                ('handler_type', models.IntegerField(blank=True, choices=[(1, '\u7528\u6237'), (2, '\u89d2\u8272'), (3, '\u90e8\u95e8'), (4, '\u5c97\u4f4d')], default=1, null=True, verbose_name='\u7ba1\u7406\u8005\u7c7b\u578b')),
                ('handler_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodebranch_handler_department_set', to='usermanager.Department', verbose_name='\u6307\u5b9a\u90e8\u95e8')),
                ('handler_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodebranch_handler_position_set', to='usermanager.UserProfile', verbose_name='\u6307\u5b9a\u5c97\u4f4d')),
                ('handler_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodebranch_handler_roles_set', to='usermanager.UserProfile', verbose_name='\u6307\u5b9a\u89d2\u8272')),
                ('handler_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodebranch_handler_user_set', to='usermanager.UserProfile', verbose_name='\u6307\u5b9a\u7528\u6237')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_modal_set', to='workflow.Node', verbose_name='\u8282\u70b9\u5206\u652f')),
            ],
            options={
                'verbose_name': '\u5de5\u4f5c\u6d41\u8282\u70b9\u5206\u652f',
                'verbose_name_plural': '\u5de5\u4f5c\u6d41\u8282\u70b9\u5206\u652f',
            },
        ),
    ]
