# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-07 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('\u5165\u5e93', '\u5165\u5e93'), ('\u9886\u7528', '\u9886\u7528'), ('\u5f52\u8fd8', '\u5f52\u8fd8'), ('\u501f\u51fa', '\u501f\u51fa'), ('\u62a5\u5e9f', '\u62a5\u5e9f'), ('\u4e22\u5931', '\u4e22\u5931'), ('\u7ef4\u4fee', '\u7ef4\u4fee')], max_length=25, verbose_name='\u7ef4\u62a4\u7c7b\u578b')),
                ('allocate_date', models.DateField(verbose_name='\u7ef4\u62a4\u65e5\u671f')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8d44\u4ea7\u8bb0\u5f55',
                'verbose_name_plural': '\u8d44\u4ea7\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.CharField(blank=True, max_length=25, null=True, verbose_name='\u8d44\u4ea7\u7f16\u53f7')),
                ('old_num', models.CharField(blank=True, max_length=25, null=True, verbose_name='\u539f\u8d44\u4ea7\u7f16\u53f7')),
                ('name', models.CharField(choices=[('\u7b14\u8bb0\u672c', '\u7b14\u8bb0\u672c'), ('\u53f0\u5f0f\u673a', '\u53f0\u5f0f\u673a'), ('\u663e\u793a\u5668', '\u663e\u793a\u5668'), ('\u624b\u673a', '\u624b\u673a'), ('\u670d\u52a1\u5668', '\u670d\u52a1\u5668'), ('\u6253\u5370\u673a', '\u6253\u5370\u673a'), ('\u7f51\u7edc\u8bbe\u5907', '\u7f51\u7edc\u8bbe\u5907'), ('\u7535\u89c6\u673a', '\u7535\u89c6\u673a'), ('iPad', 'iPad'), ('\u5176\u5b83', '\u5176\u5b83')], max_length=25, verbose_name='\u8d44\u4ea7\u540d\u79f0')),
                ('configuration', models.CharField(max_length=100, verbose_name='\u914d\u7f6e\u53c2\u6570')),
                ('sn', models.CharField(blank=True, max_length=50, null=True, verbose_name='SN')),
                ('mac', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC\u5730\u5740')),
                ('position', models.CharField(default='\u6b27\u5e94\u4fe1\u606f', max_length=50, verbose_name='\u5b58\u653e\u4f4d\u7f6e')),
                ('purchase_date', models.DateField(verbose_name='\u91c7\u8d2d\u65e5\u671f')),
                ('depreciable_lives', models.DecimalField(decimal_places=0, default=2, max_digits=10, verbose_name='\u6298\u65e7\u5e74\u9650')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u91c7\u8d2d\u4ef7\u683c(\u5143)')),
                ('residual_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u6b8b\u4f59\u4ef7\u503c(\u5143)')),
                ('status', models.CharField(choices=[('\u5165\u5e93', '\u5165\u5e93'), ('\u9886\u7528', '\u9886\u7528'), ('\u5f52\u8fd8', '\u5f52\u8fd8'), ('\u501f\u51fa', '\u501f\u51fa'), ('\u62a5\u5e9f', '\u62a5\u5e9f'), ('\u4e22\u5931', '\u4e22\u5931'), ('\u7ef4\u4fee', '\u7ef4\u4fee')], default='\u5165\u5e93', max_length=25, verbose_name='\u8d44\u4ea7\u72b6\u6001')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('applicants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_applicants', to='usermanager.UserProfile', verbose_name='\u7533\u8bf7\u4eba')),
                ('applicaton_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_applicaton_department', to='usermanager.Department', verbose_name='\u7533\u8bf7\u90e8\u95e8')),
            ],
            options={
                'verbose_name': 'IT\u8d44\u4ea7\u8868',
                'verbose_name_plural': 'IT\u8d44\u4ea7\u8868',
            },
        ),
        migrations.CreateModel(
            name='LowAllocate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('\u5165\u5e93', '\u5165\u5e93'), ('\u9886\u7528', '\u9886\u7528'), ('\u5f52\u8fd8', '\u5f52\u8fd8'), ('\u501f\u51fa', '\u501f\u51fa'), ('\u62a5\u5e9f', '\u62a5\u5e9f'), ('\u4e22\u5931', '\u4e22\u5931'), ('\u7ef4\u4fee', '\u7ef4\u4fee')], default='\u5165\u5e93', max_length=25, verbose_name='\u7ef4\u62a4\u7c7b\u578b')),
                ('is_recycled', models.BooleanField(default=False, verbose_name='\u9886\u7528\u5e93\u5b58')),
                ('nums', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='\u6570\u91cf')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='\u5355\u4ef7(\u5143)')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4f4e\u503c\u8c03\u62e8',
                'verbose_name_plural': '\u4f4e\u503c\u8c03\u62e8',
            },
        ),
        migrations.CreateModel(
            name='LowInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='\u8d44\u4ea7\u540d\u79f0')),
                ('is_recycled', models.BooleanField(verbose_name='\u53ef\u56de\u6536')),
                ('inventory', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='\u5e93\u5b58')),
                ('recycled', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='\u56de\u6536')),
                ('lose', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='\u4e22\u5931')),
                ('broken', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='\u62a5\u5e9f')),
                ('total_prices', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u603b\u4ef7')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u4f4e\u503c\u5e93\u5b58',
                'verbose_name_plural': '\u4f4e\u503c\u5e93\u5b58',
            },
        ),
        migrations.CreateModel(
            name='LowInventoryTmp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_recycled', models.BooleanField(verbose_name='\u53ef\u56de\u6536')),
                ('inventory', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='\u5e93\u5b58')),
                ('recycled', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='\u56de\u6536')),
                ('lose', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='\u4e22\u5931')),
                ('broken', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='\u62a5\u5e9f')),
                ('total_prices', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u603b\u4ef7')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowinventorytmp_name', to='assets.LowInventory', verbose_name='\u8d44\u4ea7\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u4f4e\u503c\u5e93\u5b58Tmp',
                'verbose_name_plural': '\u4f4e\u503c\u5e93\u5b58Tmp',
            },
        ),
        migrations.CreateModel(
            name='LowPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='\u5e74\u4efd')),
                ('month', models.CharField(blank=True, max_length=2, null=True, verbose_name='\u6708\u4efd')),
                ('useful_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u4f7f\u7528\u4ef7\u503c')),
                ('use_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lowprice_use_department', to='usermanager.Department', verbose_name='\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '\u4f4e\u503c\u8d39\u7528',
                'verbose_name_plural': '\u4f4e\u503c\u8d39\u7528',
            },
        ),
        migrations.CreateModel(
            name='LowPriceTmp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='\u5e74\u4efd')),
                ('month', models.CharField(blank=True, max_length=2, null=True, verbose_name='\u6708\u4efd')),
                ('useful_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u4f7f\u7528\u4ef7\u503c')),
                ('use_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lowpricetmp_use_department', to='usermanager.Department', verbose_name='\u90e8\u95e8')),
            ],
            options={
                'verbose_name': '\u4f4e\u503c\u8d39\u7528Tmp',
                'verbose_name_plural': '\u4f4e\u503c\u8d39\u7528Tmp',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('partner', models.CharField(max_length=50, verbose_name='\u5408\u4f5c\u4f19\u4f34')),
                ('partner_head', models.CharField(max_length=25, verbose_name='\u8d1f\u8d23\u4eba')),
                ('partner_tel', models.CharField(max_length=25, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5408\u4f5c\u4f19\u4f34',
                'verbose_name_plural': '\u5408\u4f5c\u4f19\u4f34',
            },
        ),
        migrations.CreateModel(
            name='PurchasingAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d44\u4ea7\u540d\u79f0')),
                ('configuration', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u89c4\u683c\u53c2\u6570')),
                ('nums', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='\u6570\u91cf')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u5355\u4ef7(\u5143)')),
                ('total_prices', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u603b\u4ef7(\u5143)')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='\u4fdd\u4fee\u5e74\u4efd')),
                ('applicaton_department', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7533\u8bf7\u90e8\u95e8')),
                ('applicants', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7533\u8bf7\u4eba')),
                ('invoice_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u53d1\u7968\u53f7')),
                ('assets_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d44\u4ea7\u7f16\u53f7')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='\u91c7\u8d2d\u65e5\u671f')),
                ('apply_date', models.DateField(blank=True, null=True, verbose_name='\u7533\u8bf7\u65e5\u671f')),
                ('is_arrival', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5230\u8d27')),
                ('is_account', models.BooleanField(default=False, verbose_name='\u662f\u5426\u62a5\u9500')),
                ('is_purchase', models.BooleanField(default=True, verbose_name='\u5f85\u91c7\u8d2d')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u91c7\u8d2d\u8bb0\u5f55',
                'verbose_name_plural': '\u91c7\u8d2d\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='UserPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='\u5e74\u4efd')),
                ('month', models.CharField(blank=True, max_length=2, null=True, verbose_name='\u6708\u4efd')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u4f7f\u7528\u4ef7\u503c')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprice_name', to='usermanager.Department', verbose_name='\u90e8\u95e8')),
            ],
            options={
                'verbose_name': 'IT\u8d39\u7528\u5206\u644a',
                'verbose_name_plural': 'IT\u8d39\u7528\u5206\u644a',
            },
        ),
        migrations.CreateModel(
            name='VideoAssets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.CharField(blank=True, max_length=25, null=True, verbose_name='\u8d44\u4ea7\u7f16\u53f7')),
                ('asset_classes', models.CharField(choices=[('\u56fa\u5b9a\u8d44\u4ea7', '\u56fa\u5b9a\u8d44\u4ea7'), ('\u8017\u6750', '\u8017\u6750')], max_length=25, verbose_name='\u8d44\u4ea7\u5206\u7c7b')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d44\u4ea7\u540d\u79f0')),
                ('configuration', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u89c4\u683c\u53c2\u6570')),
                ('sn', models.CharField(blank=True, max_length=50, null=True, verbose_name='SN\u5e8f\u5217\u53f7')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('purchaser', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u91c7\u8d2d\u4eba')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='\u91c7\u8d2d\u65e5\u671f')),
                ('partnet', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4f9b\u5e94\u5546')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u91c7\u8d2d\u4ef7\u683c(\u5143)')),
                ('applicaton_department', models.CharField(default='\u89c6\u9891\u90e8', max_length=20, verbose_name='\u7533\u8bf7\u90e8\u95e8')),
                ('applicants', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7533\u8bf7\u4eba')),
                ('status', models.CharField(choices=[('\u5165\u5e93', '\u5165\u5e93'), ('\u9886\u7528', '\u9886\u7528'), ('\u5f52\u8fd8', '\u5f52\u8fd8'), ('\u501f\u51fa', '\u501f\u51fa'), ('\u62a5\u5e9f', '\u62a5\u5e9f'), ('\u4e22\u5931', '\u4e22\u5931'), ('\u7ef4\u4fee', '\u7ef4\u4fee')], default='\u5165\u5e93', max_length=25, verbose_name='\u8d44\u4ea7\u72b6\u6001')),
                ('use_department', models.CharField(default='\u89c6\u9891\u90e8', max_length=20, verbose_name='\u4f7f\u7528\u90e8\u95e8')),
                ('user', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4f7f\u7528\u4eba')),
                ('asset_num', models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='\u8d44\u4ea7\u6570\u91cf')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u89c6\u9891\u8d44\u4ea7',
                'verbose_name_plural': '\u89c6\u9891\u8d44\u4ea7',
            },
        ),
        migrations.AddField(
            model_name='lowallocate',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowallocate_name', to='assets.LowInventory', verbose_name='\u8d44\u4ea7\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='lowallocate',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='low_allocate_operator', to='usermanager.UserProfile', verbose_name='\u7ecf\u529e\u4eba'),
        ),
        migrations.AddField(
            model_name='lowallocate',
            name='partnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Partner', verbose_name='\u4f9b\u5e94\u5546'),
        ),
        migrations.AddField(
            model_name='lowallocate',
            name='use_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lowallocate_use_department', to='usermanager.Department', verbose_name='\u90e8\u95e8'),
        ),
        migrations.AddField(
            model_name='lowallocate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lowallocate_user', to='usermanager.UserProfile', verbose_name='\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='assets',
            name='partnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Partner', verbose_name='\u4f9b\u5e94\u5546'),
        ),
        migrations.AddField(
            model_name='assets',
            name='purchaser',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.CASCADE, related_name='assets_purchaser', to='usermanager.UserProfile', verbose_name='\u91c7\u8d2d\u4eba'),
        ),
        migrations.AddField(
            model_name='assets',
            name='use_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_use_department', to='usermanager.Department', verbose_name='\u4f7f\u7528\u90e8\u95e8'),
        ),
        migrations.AddField(
            model_name='assets',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_user', to='usermanager.UserProfile', verbose_name='\u4f7f\u7528\u4eba'),
        ),
        migrations.AddField(
            model_name='allocate',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocate_num', to='assets.Assets', verbose_name='\u8d44\u4ea7\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='allocate',
            name='use_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocate_use_department', to='usermanager.Department', verbose_name='\u4f7f\u7528\u90e8\u95e8'),
        ),
        migrations.AddField(
            model_name='allocate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocate_user', to='usermanager.UserProfile', verbose_name='\u4f7f\u7528\u4eba'),
        ),
    ]
