# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-30 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_department', models.CharField(max_length=25, verbose_name='\u4e00\u7ea7\u90e8\u95e8')),
                ('two_department', models.CharField(max_length=25, verbose_name='\u4e8c\u7ea7\u90e8\u95e8')),
                ('first_leader', models.CharField(max_length=25, verbose_name='\u4e00\u7ea7\u9886\u5bfc')),
                ('two_leader', models.CharField(max_length=25, verbose_name='\u4e8c\u7ea7\u9886\u5bfc')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u90e8\u95e8\u7ba1\u7406',
                'verbose_name_plural': '\u90e8\u95e8\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='\u59d3\u540d')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u90ae\u4ef6')),
                ('tel', models.CharField(blank=True, max_length=25, null=True, verbose_name='\u7535\u8bdd')),
                ('status', models.CharField(blank=True, choices=[('\u8bd5\u7528\u671f', '\u8bd5\u7528\u671f'), ('\u5df2\u8f6c\u6b63', '\u5df2\u8f6c\u6b63'), ('\u5df2\u79bb\u804c', '\u5df2\u79bb\u804c')], max_length=25, null=True, verbose_name='\u72b6\u6001')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='\u5165\u804c\u65e5\u671f')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_department', to='usermanager.Department', verbose_name='\u90e8\u95e8')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_user', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'verbose_name': '\u5458\u5de5\u4fe1\u606f',
                'verbose_name_plural': '\u5458\u5de5\u4fe1\u606f',
            },
        ),
    ]
