# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DhcpBind',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('10.0.0.0', '10.0.0.0-10.0.7.254'), ('10.1.0.0', '10.1.0.0-10.1.1.254'), ('10.1.6.0', '10.1.6.0-10.1.7.254'), ('10.1.8.0', '10.1.8.0-10.1.9.254')], max_length=30, verbose_name='\u8303\u56f4')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('mac', models.CharField(max_length=20, verbose_name='MAC')),
                ('describe', models.CharField(choices=[('phone', 'phone'), ('pc', 'pc')], max_length=20, verbose_name='\u63cf\u8ff0')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('judge', models.BooleanField(verbose_name='\u529e\u516c\u8bbe\u5907')),
                ('state', models.BooleanField(verbose_name='\u4f7f\u7528\u4e2d')),
                ('cmd', models.TextField(blank=True, max_length=150, null=True, verbose_name='\u547d\u4ee4')),
            ],
            options={
                'verbose_name': 'DHCP\u7ed1\u5b9a',
                'verbose_name_plural': 'DHCP\u7ed1\u5b9a',
            },
        ),
        migrations.CreateModel(
            name='ItManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('model', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u578b\u53f7')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP')),
                ('system', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u7cfb\u7edf')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5bc6\u7801')),
                ('link', models.URLField(blank=True, null=True, verbose_name='\u94fe\u63a5')),
                ('tel', models.CharField(blank=True, max_length=80, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('application', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5e94\u7528')),
                ('remarks', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u4f7f\u7528\u4e2d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itmanager_dep_set', to='usermanager.Department', verbose_name='\u4f7f\u7528\u90e8\u95e8')),
            ],
            options={
                'verbose_name': 'IT\u8fd0\u7ef4\u4fe1\u606f',
                'verbose_name_plural': 'IT\u8fd0\u7ef4\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='ItRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=24, null=True, verbose_name='IP')),
                ('system', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u7cfb\u7edf')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5bc6\u7801')),
                ('application', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5e94\u7528')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itrecord_name_set', to='itmanager.ItManager', verbose_name='\u7cfb\u7edf')),
            ],
            options={
                'verbose_name': 'IT\u8fd0\u7ef4\u8be6\u60c5\u8bb0\u5f55',
                'verbose_name_plural': 'IT\u8fd0\u7ef4\u8be6\u60c5\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='WrokOrders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_date', models.DateField(verbose_name='\u95ee\u9898\u65e5\u671f')),
                ('pro_desc', models.TextField(blank=True, null=True, verbose_name='\u95ee\u9898\u63cf\u8ff0')),
                ('solver', models.CharField(blank=True, help_text='\u591a\u4e2a\u89e3\u51b3\u4eba\u65f6\u7528\u82f1\u6587\u9017\u53f7\u5206\u9694', max_length=100, null=True, verbose_name='\u89e3\u51b3\u4eba')),
                ('solve_len_time', models.DecimalField(decimal_places=2, default=0, help_text='\u6700\u5c0f\u5355\u4f4d0.25\u537315\u5206\u949f', max_digits=10, verbose_name='\u5de5\u65f6(\u5c0f\u65f6)')),
                ('solve_desc', models.TextField(blank=True, null=True, verbose_name='\u89e3\u51b3\u65b9\u6cd5')),
                ('is_finish', models.BooleanField(default=False, verbose_name='\u5df2\u5b8c\u6210')),
                ('creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u521b\u5efa\u8005')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('org_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workorders_org_dept', to='usermanager.Department', verbose_name='\u53d1\u8d77\u90e8\u95e8')),
                ('org_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders_org_user', to='usermanager.UserProfile', verbose_name='\u53d1\u8d77\u4eba')),
            ],
            options={
                'verbose_name': '\u5de5\u5355\u8bb0\u5f55',
                'verbose_name_plural': '\u5de5\u5355\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='WrokOrdersType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u95ee\u9898\u7c7b\u578b')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5de5\u5355\u7c7b\u578b',
                'verbose_name_plural': '\u5de5\u5355\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='wrokorders',
            name='pro_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders_pro_type', to='itmanager.WrokOrdersType', verbose_name='\u95ee\u9898\u7c7b\u578b'),
        ),
    ]
