# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-05 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetApplicationProcess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=6, null=True, verbose_name='\u7f16\u7801')),
                ('assets_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8d44\u4ea7\u540d\u79f0')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AssetApplicationProcess_department_set', to='usermanager.Department', verbose_name='\u4f7f\u7528\u90e8\u95e8')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AssetApplicationProcess_user_set', to='usermanager.UserProfile', verbose_name='\u4f7f\u7528\u4eba')),
            ],
            options={
                'verbose_name': '\u8d44\u4ea7\u7533\u8bf7\u6d41\u7a0b',
                'verbose_name_plural': '\u8d44\u4ea7\u7533\u8bf7\u6d41\u7a0b',
            },
        ),
    ]
